google/eleventy-high-performance-blog

_11ty/optimize-html.js

If you set `permalink: false` in the frontmatter for a post then `outputPath` will either be `null` or `undefined` (can't recall which off the top of my head). This causes the attempt to use `endsWith()` to throw.
Changes proposed:
- Adds check for the existence of `outputPath` before attempting to use `endsWith()`

Check for undefined outputPath

---

_11ty/optimize-html.js

This setting omits e.g. `</li>` and `</p>` where possible (which is still valid HTML).

Enable removeOptionalTags html-minifier setting

---

README.md
_11ty/img-dim.js
css/main.css

This makes it so that:
- Images are only decoded/rasterized when needed.
- The blurry placeholder (which can be expensive) is only ever rendered when images enter the viewport before they load.
The main work here is to generate the correct value for `contain-intrinsic-size`. This is achieved by:
- Defining a CSS variable with the width of the main article body
- Expressing the `contain-intrinsic-size` as a function of this and the image aspect ratio.
- Using the images `width` and `height`` as ceiling for the intrinsic size.
More info https://web.dev/content-visibility/#skipping-rendering-work-with-content-visibility

Make images `content-visibility: auto`

---

css/main.css

"Content-visibility: auto" moves the images over the other elements.
Set z-index to keeps the nav over the rasterized images.

Fix images over navbar

---

.eleventyignore

The folder being ignored is automatically brought in by Azure Static Website's default deployment mechanism, and will break the default build process of eleventy. Ignoring it fixes the issue of trying to syntax highlight files in that directory

Add oryx_prod_node_modules to fix compatibility with Azure Websites

---

test/test-generic-post.js

This PR helps updating the test `should have script elements` easier: you only need to change ***one number*** instead of two in the old version.

Make updating the test "should have script elements" easier

---

tags.njk

`<h1>Tagged “{{ tag }}”</h1>` is redundant since we already render the title `Tagged “{{ tag }}”`

Remove the redundant <h1>Tagged “{{ tag }}”</h1>

---

tags.njk

11ty fails to write the tag folder if you've got a tag like `c#`.

Fix bug where tags contain illegal path characters like #

---

.eleventy.js

It seems that tagList collection was accidentaly deleted in a previous commit.
This commit restore it to make **All tags** page working (/tags/).

Restore tagList collection

---

src/main.js

Add a check against the prospective href to prefetch:
Is the href equal to the current page?

Prevent duplicate link rel prefetches and prefetching the current page

---

.eleventyignore

The error was reported at https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/issues/18. 
Since Netlify is also a growing service for hosting static sites, this will save people a lot of time debugging.

.eleventyignore: Also ignore .netlify/ to avoid template rendering error

---

tags-list.njk

Hello @cramforce,
I'm using tags with spaces (e.g. "Small Business"). Currently this leads to 404s as the links on the `/tags`-page aren't created correctly. This change pipes the tags through slug to fix it.
Cheers,
Peter

Allow for tags with spaces

---

_includes/layouts/base.njk
posts/fifthpost.md

When a post has `permalink` set to false, though no output file is
generated, the file is still processed with the `url` property set to
false. Thus, the expression in base.njk testing the `url` property must
ensure page.url is defined in advance.

Ensure page.url is defined before dereferncing it

---

package-lock.json
package.json

Updates the `ffmpeg-static` dependency to v4.4.0 which adds [native support for Apple Silicon](https://github.com/eugeneware/ffmpeg-static/issues/83#issuecomment-866011992).

Bump ffmpeg-static from 4.2.7 to 4.4.0

---

.eleventy.js
README.md
_11ty/apply-csp.js
_data/csp.js
_headers
_includes/layouts/base.njk
test/test-generic-post.js

An injection before the meta tag will bypass the CSP. Additionally, frame-ancestors, sandbox and reporting are not supported in meta tag CSPs. (https://web.dev/csp-xss/?utm_source=lighthouse&utm_medium=devtools#define-the-csp-in-an-http-header)
This pull request should be ensure CSP is effective against XSS attacks
Changes
1. Remove meta tag from base template
2. Add a block text to _header that will be replaced with the CSP headers
3. Write the CSP headers when run apply-csp (create an header for both full url and Pretty URL)
4. Override Browser-Synch configuration to read CSP headers from _headers file
5. Remove check for CSP meta tag in test (somebody can write a better test to check for a CSP header in _headers)

Use CSP header instead of meta tag

---

_11ty/img-dim.js
_11ty/srcset.js
posts/secondpost.md
src/main.js

- Removes the race condition where memory cached images may keep their blurred images in the background which shine through with transparent foreground images.
- Fallback to PNG instead of JPEG if the input image is a PNG. Keeps AVIF and WEBP lossy compression as they do support transparency.
Fixes #120

Avoid issues with blurred images and transparency. Correctly handle PNG source images

---

.eleventy.js
_data/isdevelopment.js
package-lock.json
package.json
posts/fifthpost.md
tags-list.njk
tags.njk
test/test-post-drafted.js

`s/slug/slugify`
- More robust test triggering (Now gets triggered by test changes or by the build actually finishing)
- Fixed bad tests for draft posts.
Changed the `addHash` filter to read from source directories instead of `_site`. This works but it would not work if a file would be synthesized into the output dir. This is necessary due to a race condition that only happens in `watch` mode where `_site` doesn't exist during re-build.

Upgrade to eleventy 1.0 🎉

---

.eleventy.js

In the old behaviour, when the user changes the content of `404.md`, they would need to restart the dev server in order for the change to take effect. This change effectively fixes the issue.

fix(eleventyConfig): read 404.html on demand

---

css/main.css

Code syntax highlight style broken when without given language (screenshot in below).
Update style for `without given language`
- The value of `padding`, `background`, `color` are **SAME** with  other existed `<pre />, <code /> style`
Past following text into any **Markdown** file and review it
> **```**
> redis> zrange zset 0 -1
> 1. "b"
> 2. "ba"
> 3. "bar"
> 4. "bar*"
> 5. "f"
> 6. "fo"
> 7. "foo"
> 8. "foo*"
> 9. "foob"
> 10. "fooba"
> 11. "foobar"
> 12. "foobar*"
> **```**
Currently **Firefox did NOT support `:has()`** yet, but it's looks acceptable (for this small fix).
See **Firefox screenshot** in blow

Fix code syntax highlight style issue when without given language

---

.eleventy.js
_11ty/apply-csp.js

A compatibility issue with Eleventy v2.x came up after a recent merge request "Bump axios and @11ty/eleventy #180". It updated Eleventy from 1.0.0 to 2.0.1
https://github.com/google/eleventy-high-performance-blog/actions/runs/6827178225/job/18568727206
In Eleventy v2 [Eleventy Dev Server](https://www.11ty.dev/docs/dev-server/) replaces Browsersync (https://github.com/11ty/eleventy/issues/1305).
So I removed the Browsersync related code.
[Eleventy Dev Server](https://www.11ty.dev/docs/dev-server/) has built-in support for `404.html`. 
And there is no need for additional CSP code.

Remove Browsersync for Eleventy v2.x compatibility
